services:
  redis:
    image: 'redis:7.0.11'
    ports:
      - '6379'
  mysql:
    image: 'mysql:8.0.33'
    ports:
      - '3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: cocsi
